services:
  credit-api:
    build: .
    env_file: 
     - path: ./.env
       required: true # default
    container_name: credit_scoring_api
    ports:
      - "8000:8000"
      - "5678:5678"
    volumes:
      - sqlite_data:/app/data
    develop:
      watch:
        - action: sync
          path: ./src
          target: /app/src
          initial_sync: true
        - action: rebuild
          path: requirements.txt
    environment:
      DATABASE_PATH: ${DATABASE_PATH}
    restart: unless-stopped

volumes:
  sqlite_data:
