version: "3.9"

services:
  credit-api:
    build: .
    container_name: credit_scoring_api
    ports:
      - "8000:8000"
    volumes:
      - sqlite_data:/app/data
    environment:
      - DATABASE_URL=sqlite:////app/data/credit.db
    restart: unless-stopped

volumes:
  sqlite_data:
